#!/bin/sh

copy() {
	printf "Copying %s to %s\n" "$1" "$2"

	cp -frT "$1" "$2"
}

if [ ! "$1" ]
then
	printf 'Preset not specified\n'

	exit 1
elif [ ! -r "presets/$1.sh" ]
then
	printf 'Preset not found\n'

	exit 1
fi

XDG_CONFIG_HOME="${XDG_CONFIG_HOME:=$HOME/.config}"

mkdir -p "$HOME/.config"

for preset in "$@"
do
	. "presets/$preset.sh"
done
