exec-once=waybar

tagrule=id:5,open_as_floating:1

tag_num=5
default_mfact=0.6

borderpx=4

rootcolor=0x000000ff
urgentcolor=0xf9e2afff
dropcolor=0xf9e2afff
bordercolor=0x1e1e2eff
focuscolor=0x7f849cff

gappiv=0
gappih=0
gappov=0
gappoh=0

animations=0
blur=0
shadows=0

xkb_rules_layout=pt

bind=super,r,reload_config

bind=super,p,spawn,$(pkill wofi || wofi -S drun)
bind=super+shift,p,spawn,$(pkill wofi || wofi -S run)
bind=super+shift,Return,spawn,foot

bind=super+shift,q,quit
bind=super+shift,c,killclient,

bind=super,j,focusstack,next
bind=super,k,focusstack,previous

bind=super+shift,j,resizewin,+0,+20
bind=super+shift,k,resizewin,+0,-20
bind=super+shift,h,resizewin,-20,+0
bind=super+shift,l,resizewin,+20,+0

mousebind=super,btn_left,moveresize,curmove
mousebind=super,btn_right,moveresize,curresize

bind=super,1,view,1,0
bind=super,2,view,2,0
bind=super,3,view,3,0
bind=super,4,view,4,0
bind=super,5,view,5,0

bind=super+shift,1,tagsilent,1,0
bind=super+shift,2,tagsilent,2,0
bind=super+shift,3,tagsilent,3,0
bind=super+shift,4,tagsilent,4,0
bind=super+shift,5,tagsilent,5,0

bind=super,f,togglefloating

bind=super+shift,0,toggleoverview,0
bind=super,0,toggleoverview,1
